[project]
name = "mas-sk-quickstart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-identity>=1.20.0",
    "ipykernel>=6.29.5",
    "python-dotenv>=1.0.1",
    "semantic-kernel>=1.21.1",
]
